#!/bin/sh

MAESTRO_BUNDLE_LOC=/usr/local/bin/maestro-bundle
MAESTRO_SYMLINK_LOC=/usr/local/bin/maestro

# Remove bundle files
echo Removing maestro bundle files at $MAESTRO_BUNDLE_LOC
rm -rf $MAESTRO_BUNDLE_LOC  || echo Failed to remove maestro bundle files at $MAESTRO_BUNDLE_LOC, try running with sudo

# Remove symlink
echo Removing symlink at $MAESTRO_SYMLINK_LOC
rm -rf $MAESTRO_SYMLINK_LOC || echo Failed to remove maestro symlink at $MAESTRO_SYMLINK_LOC, try running with sudo

echo "Uninstall complete; maestro data at ~/.maestro-files has not been deleted"