#!/bin/sh

MAESTRO_BUNDLE_LOC=/usr/local/bin/maestro-bundle
MAESTRO_SYMLINK_LOC=/usr/local/bin/maestro

# Make maestro executable
chmod +x $MAESTRO_BUNDLE_LOC/maestro

# Recursively find and disable quarantine
find $MAESTRO_BUNDLE_LOC -exec sudo xattr -d com.apple.quarantine {} +

# Remove existing symlink
rm -rf $MAESTRO_SYMLINK_LOC

# Create a symlink to the maestro executable
ln -s $MAESTRO_BUNDLE_LOC/maestro $MAESTRO_SYMLINK_LOC