name: Cross-Platform Build
on: push
jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          # pyinstaller_ver: '==6.9.0'
          spec: 'maestro/maestro.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-windows'
          options: --onefile, --name "maestro", --icon "data/icons/maestro_icon.ico", --noupx
  pyinstaller-build-mac:
    runs-on: macos-12
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          # pyinstaller_ver: '==6.9.0'
          spec: 'maestro/maestro.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-mac'
          options: --onefile, --name "maestro", --icon "data/icons/maestro_icon.icns", --noupx
  pyinstaller-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          # pyinstaller_ver: '==6.9.0'
          spec: 'maestro/maestro.py'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-ubuntu'
          options: --onefile, --name "maestro", --noupx
