name: Cross-Platform Build

on: push

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: maestro-onedir.spec
          requirements: requirements.txt
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: maestro-windows
          path: ./dist/maestro
          # options: --icon "data/icons/maestro_icon.ico"
  pyinstaller-build-mac:
    runs-on: macos-12
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: maestro-onedir.spec
          requirements: requirements.txt
          # options: --icon "data/icons/maestro_icon.icns"
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: maestro-mac
          path: ./dist/maestro
      # - name: Create .pkg
      #   uses: akiojin/generate-mac-installer-github-action@v0.1.3
      #   with:
      #     root-directory:  # TODO
      #     identifier: com.maestro.maestro-cli
      #     version: '1.1.1'
      #     install-location: /Applications
  pyinstaller-build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: maestro-onedir.spec
          requirements: requirements.txt
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: maestro-ubuntu
          path: ./dist/maestro
