name: Cross-Platform Build

on: push

jobs:
  pyinstaller-build-windows:
    runs-on: windows-latest
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'maestro.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-windows'
          # options: --icon "data/icons/maestro_icon.ico"
  pyinstaller-build-mac:
    runs-on: macos-12
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'maestro.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-mac'
          # options: --icon "data/icons/maestro_icon.icns"
  pyinstaller-build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Build executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'maestro.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'maestro-ubuntu'
